/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	appdeploymentv1alpha1 "github.com/soniabha-intc/edgedeploy/pkg/crd/appdeployment/v1alpha1"
	versioned "github.com/soniabha-intc/edgedeploy/pkg/crd/appdeployment/v1alpha1/apis/clientset/versioned"
	internalinterfaces "github.com/soniabha-intc/edgedeploy/pkg/crd/appdeployment/v1alpha1/apis/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/soniabha-intc/edgedeploy/pkg/crd/appdeployment/v1alpha1/apis/listers/appdeployment/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AppDeploymentInformer provides access to a shared informer and lister for
// AppDeployments.
type AppDeploymentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AppDeploymentLister
}

type appDeploymentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAppDeploymentInformer constructs a new informer for AppDeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAppDeploymentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAppDeploymentInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAppDeploymentInformer constructs a new informer for AppDeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAppDeploymentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppdeploymentV1alpha1().AppDeployments(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppdeploymentV1alpha1().AppDeployments(namespace).Watch(context.TODO(), options)
			},
		},
		&appdeploymentv1alpha1.AppDeployment{},
		resyncPeriod,
		indexers,
	)
}

func (f *appDeploymentInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAppDeploymentInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *appDeploymentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&appdeploymentv1alpha1.AppDeployment{}, f.defaultInformer)
}

func (f *appDeploymentInformer) Lister() v1alpha1.AppDeploymentLister {
	return v1alpha1.NewAppDeploymentLister(f.Informer().GetIndexer())
}
