# INTEL CONFIDENTIAL
#
# Copyright 2020-2020 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: "{{ .Values.service.name }}"
  name: edgedeployagent
  namespace: "{{ .Values.namespace }}"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      service: "{{ .Values.service.name }}"
  template:
    metadata:
      labels:
        service: "{{ .Values.service.name }}"
      name: edgedeployagent
      namespace: "{{ .Values.namespace }}"
    spec:  
      serviceAccountName: "{{ .Values.service_account }}"    
      volumes:
       - name: configs-edgedeploy
         configMap:
            name: "{{ .Values.configmap.edgedeploy }}"
      containers:
        - name: edgedeploy-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          volumeMounts:
            - name: configs-edgedeploy
              mountPath: /home/edgedeploy/configs/edgedeploy.json
              subPath: edgedeploy.json
          securityContext:
            privileged: false
          env:
          - name: no_proxy
            value: localhost,127.0.0.1
