# INTEL CONFIDENTIAL
#
# Copyright 2020-2020 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.service_account }}"
  namespace: "{{ .Values.namespace }}"
automountServiceAccountToken: true

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: "{{ .Values.namespace }}"
  name: "{{ .Values.role }}"
rules:
- apiGroups: ["apiextensions.k8s.io","smartedge.intel.com",""] # "" indicates the core API group
  resources: ["appdeployments","customresourcedefinitions","coredeployments"]
  verbs: ["get", "watch", "list", "create", "update", "delete", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Values.role_binding }}"
  namespace: "{{ .Values.namespace }}"
subjects:
- kind: ServiceAccount
  name: "{{ .Values.service_account }}"
  namespace: "{{ .Values.namespace }}"
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: "{{ .Values.role }}" # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
