/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	coredeploymentv1alpha1 "github.com/soniabha-intc/edgedeploy/pkg/crd/coredeployment/v1alpha1"
	versioned "github.com/soniabha-intc/edgedeploy/pkg/crd/coredeployment/v1alpha1/apis/clientset/versioned"
	internalinterfaces "github.com/soniabha-intc/edgedeploy/pkg/crd/coredeployment/v1alpha1/apis/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/soniabha-intc/edgedeploy/pkg/crd/coredeployment/v1alpha1/apis/listers/coredeployment/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CoreDeploymentInformer provides access to a shared informer and lister for
// CoreDeployments.
type CoreDeploymentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CoreDeploymentLister
}

type coreDeploymentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCoreDeploymentInformer constructs a new informer for CoreDeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCoreDeploymentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCoreDeploymentInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCoreDeploymentInformer constructs a new informer for CoreDeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCoreDeploymentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoredeploymentV1alpha1().CoreDeployments(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoredeploymentV1alpha1().CoreDeployments(namespace).Watch(context.TODO(), options)
			},
		},
		&coredeploymentv1alpha1.CoreDeployment{},
		resyncPeriod,
		indexers,
	)
}

func (f *coreDeploymentInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCoreDeploymentInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *coreDeploymentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&coredeploymentv1alpha1.CoreDeployment{}, f.defaultInformer)
}

func (f *coreDeploymentInformer) Lister() v1alpha1.CoreDeploymentLister {
	return v1alpha1.NewCoreDeploymentLister(f.Informer().GetIndexer())
}
